### PR TITLE
Update EntitySeat.java

### PR DESCRIPTION
**Pull request by Demitto**
fix a bug that ammo of PassengerGun is Infinity

### CODE REVIEW

**Comment by Demitto** [comment]
Is there a problem?

**Comment by Demitto** [comment]
I have already test it on client/server

**Comment by ChrisLane** [comment]
Hmm well when I tested it, ammo still seemed to be infinite but I'll try again.

**Comment by Demitto** [comment]
really? ok, let me confirm.

**Comment by Demitto** [comment]
Do you try it on Survival mode? Ammo is infinity on Creative Mode.

**Comment by Demitto** [comment]
Fix a bug that Ammo is infinity when Item durability of ammo is set in minus.

**Comment by ChrisLane** [comment]
Tested on a lancaster. Seat 1 ran out of ammo as expected however the behaviour is still not correct for any other seats.
The rear and central gunners never seemed to run out of ammo.

Also, the main guns on a helicopter will never run out of ammo still. (Tested with an Apache).

**Comment by Demitto** [comment]
It's not my mistake.
I found the bug that Shell, Missile and Bomb of All Vehicle is not working correctly.
All Shell, Missile and Bomb doesn't run out of ammo.
I fixed only the bug that second gunner seat.  It was said in an inappropriate way. My bad.

**Comment by Demitto** [comment]
I fixed the bug that Shell, Missile and Bomb of All Vehicle is not working correctly.
So, I'll make another pull requests.

**Pull request closed without merging**
