### PR TITLE
Small update

### PR DESCRIPTION
**Pull request by SteveTheEngineer**
Added run over possibility, made SquashMobs option global, added MorePlayerModels support.

### CODE REVIEW

**Comment by mensreaMC** [comment]
Does this build work?

**Comment by border999** [comment]
when this becomes an official build for Flan's I'd love to try it.

**Comment by SteveTheEngineer** [comment]
> when this becomes an official build for Flan's I'd love to try it.

Why???

**Comment by SteveTheEngineer** [comment]
I'll fix some conflicts later

**Comment by border999** [comment]
@TSEngineer It's because I like using this mod but the latest version of it for 1.12.2 has been giving me lots of problems, so I pulled it. Hoping that an update would have fixes for those issues.

**Comment by mensreaMC** [comment]
Yeah I'm excited to be able to make vehicles behave at least a little bit more realistically. Flans mod could use some cool stuff like this. Think it's possible to add potion effects for gun accuracy/kick/reload speed?

**Comment by SteveTheEngineer** [comment]
Resolved.


> Yeah I'm excited to be able to make vehicles **behave at least a little bit more realistically**. Flans mod could use some cool stuff like this. Think it's possible to add potion effects for gun accuracy/kick/reload speed?

What do you mean by "bit more realistically"? Is it run over possibility?

**Comment by mensreaMC** [comment]
Yeah, exactly that. In your opinion is the accuracy/reload speed/kick potions viable, or if I try to add it will I be wasting my time?

**Comment by SteveTheEngineer** [comment]
> Yeah, exactly that. In your opinion is the accuracy/reload speed/kick potions viable, or if I try to add it will I be wasting my time?

Maybe I'll make potions but it will not be "realistic". I am not sure about that.
If you want, I can give you an unofficial build

**Comment by SteveTheEngineer** [comment]
Additionally, about MorePlayerModels support, when driver runs over other player, he will lie down

**Comment by mensreaMC** [comment]
Yeah I didn't mean to imply that I was looking for realism in general, just with the squash mobs thing. The potion request was actually a long running wish of mine for a Fallout mod-pack I'm developing: the ability to incrementally improve accuracy for weapons in certain skill lines. I'd love to try the unofficial build.

**Comment by SteveTheEngineer** [comment]
[Flan's Mod-1.12.2-5.5.3 UNOFFICIAL.zip](https://github.com/FlansMods/FlansMod/files/2518271/Flan.s.Mod-1.12.2-5.5.3.UNOFFICIAL.zip)

**Comment by SteveTheEngineer** [comment]
Default mass is 1.0 (1 ton).
You can change it in vehicle config file, just write Mass \<tons\>.
Example:
...
Mass 1.454
...
This will set mass to 1454 kg

**Comment by SteveTheEngineer** [comment]
Also you can add MorePlayerModels into your modpack and see that player you ran over will lie down

**Comment by SteveTheEngineer** [comment]
[FlansMod 5.5.3 UNOFFICIAL.zip](https://github.com/FlansMods/FlansMod/files/2518656/FlansMod.5.5.3.UNOFFICIAL.zip)
Fixed builded

**Comment by SteveTheEngineer** [comment]
ALSO: This update will not work on external servers. (Crash when you running over anyone)

**Comment by SteveTheEngineer** [comment]
I will fix it later

**Comment by ChrisLane** [comment]
Closed due to mentioned crashes and too many features in one PR.

**Pull request closed without merging**
