### PR TITLE
Added missing Simplified Chinese translations

### PR DESCRIPTION
**Pull request by Ximu-Luya**
Added missing Simplified Chinese translations for FlansMod-jar
Added almost complete Simplified Chinese translations for Modern.Warfare-Content.Pack

In FlansMod-jar: 
I have encountered some problems, the lang file in the main module, the setting "key.rollRight.desc=Roll right" translation does not take effect. It still shows English. 
The setting "key.reloadModels.desc=Reload models", I still don't know what it can do, so I can't translate it. 

In Modern.Warfare-Content.Pack: 
In the Modern.Warfare-Content.Pack, the following paragraph: 
/*
item.MBTAPShell.name=MBT AP Tank Shell
item.MBTAPCRShell.name=MBT APCR Tank Shell
item.MBTHEShell.name=MBT HE Tank Shell
item.MBTHEShell.name=MBT HE Tank Shell
*/
There are repeated "MBT HE Tank Shell",  and the "MBT APCR Tank Shell" cannot be found in the game. And the translation of these four lines is invalid. In the game, only two items can be found, namely "AP Tank Shell" and "HE Tank Shell". I have already written the translation of these two items in this lang file. If you can fix this problem, could you please  completed the translation of these two items?

Here are the names of 4 items I cannot find in the lang file. They are "Large Bomb", "Napaml", "Small Bomb" and "Blow Torch". Their translations are “大型炸弹”, “凝固汽油炸弹”, “小型炸弹”, and “维修喷枪”. If you can fix this problem, could you please complete the translation of the names of the 4 items I wrote?

### CODE REVIEW

**Comment by ChrisLane** [comment]
Hi, thanks for the pull request!
I've removed the MBTAP... items now so you can remove those.
The "Large Bomb", "Napalm", "Small Bomb" and "Blow Torch" are all in the `run/Flan/Parts Pack` content pack

**Comment by Ximu-Luya** [comment]
OK, Thank you for your response. 
I have understood the situation, I will update the translation of `run/Flan/Parts Pack` today.

**Comment by Ximu-Luya** [comment]
Hi! I have completed the translation of the **Parts Pack** package you mentioned, and re-proofed the translation completed before. I hope to get your reply.

**Comment by ChrisLane** [comment]
Thanks, that will be included in the next release.

**Comment by Ximu-Luya** [comment]
I am very happy to contribute to this module. 
When I experienced it in the survival mode, I found that there was too little gunpowder to synthesize various firearms. Could you please add some ores or items that produce these firearms raw materials?
Maybe I’m not proficient enough, I hope you can tell me how to get raw materials in large quantities in survival mode?

**Comment by ChrisLane** [comment]
@Ximu-Luya There's a recipe for gunpowder that is added by Flan's Mod.
3 charcoal, 1 glowstone

Alternatively, if you have that recipe disabled you could make a dark room spawner to automate your monster killing.

**Comment by Ximu-Luya** [comment]
Oh. Thanks.

**Pull request merged**
